#!/bin/bash

echo "🔧 Setting up environment files for Scalecall Claude with Gemini 2.5 Flash"

# Wait for Docker if needed
echo "⏳ Waiting for Docker to be ready..."
until docker info > /dev/null 2>&1; do
    echo "   Docker not ready, waiting 3 seconds..."
    sleep 3
done
echo "✅ Docker is ready"

# Start Supabase and capture output
echo "🚀 Starting Supabase local instance..."
npx supabase start > supabase_output.tmp 2>&1

if [ $? -eq 0 ]; then
    echo "✅ Supabase started successfully"
    
    # Extract the actual keys from supabase start output
    ANON_KEY=$(grep "anon key:" supabase_output.tmp | awk '{print $3}')
    SERVICE_KEY=$(grep "service_role key:" supabase_output.tmp | awk '{print $3}')
    JWT_SECRET=$(grep "JWT secret:" supabase_output.tmp | awk '{print $3}')
    
    # Create the .env file
    cat > .env << EOF
# Supabase Local Development Configuration
# Generated by setup_env.sh on $(date)
SUPABASE_URL=http://127.0.0.1:54321
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
SUPABASE_JWT_SECRET=${JWT_SECRET}

# LLM Configuration - IMPORTANT: Using Gemini 2.5 Flash
LLM_PROVIDER=gemini
GEMINI_API_KEY="AIzaSyATHQOhKjQT0RweOQ-PF3lqT0uzlGKx0nc"

# Database Configuration
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres

# Application Settings
DEBUG=true
LOG_LEVEL=info
EOF

    # Create frontend .env
    cat > frontend/.env.local << EOF
# Frontend Environment Variables
# Generated by setup_env.sh on $(date)
VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_ANON_KEY=${ANON_KEY}
VITE_API_URL=http://localhost:8000
EOF

    echo "✅ Created .env files with local Supabase configuration"
    echo ""
    echo "🔑 Next steps:"
    echo "1. Add your real Gemini API key to .env: GEMINI_API_KEY=your-key-here"
    echo "2. Run database migrations: npx supabase db push"
    echo "3. Start the backend: cd backend && python -m uvicorn app:app --reload"
    echo "4. Start the frontend: cd frontend && npm run dev"
    echo ""
    echo "🌐 Access points:"
    echo "   Supabase Studio: http://127.0.0.1:54323"
    echo "   Backend API: http://localhost:8000"
    echo "   Frontend: http://localhost:5173"
    
    # Clean up temp file
    rm -f supabase_output.tmp
    
else
    echo "❌ Failed to start Supabase"
    cat supabase_output.tmp
    rm -f supabase_output.tmp
    exit 1
fi
